account/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "account"

urlpatterns = [
    # path('', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', index, name='home-index'),
    path('<int:id>/', retrieve, name='report-retrieve')
]

tp1ppw/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from home.views import index as home_index
from account.views import *
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#from news.views import news_page
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('account/register/', register, name='register'),
    # path('account/login/', login, name='login_user'),
    # path('account/', include('django.contrib.auth.urls')),
	path('account/', include('account.urls', namespace='account')),
    path('donation/', include('donation.urls'), name='donation'),
    path('home/', include('home.urls'), name='home'),
    path('news/', include('news.urls'), name='news'),
    path('about/', include('about.urls'), name='about'),
	path('auth/', include('social_django.urls', namespace='auth')),
    path('', index, name='index'),
    path('donatur/', include('donatur.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += staticfiles_urlpatterns()

home/models.py
from django.db import models

# Create your models here

class Report(models.Model):
	title = models.CharField(max_length=200)
	image = models.ImageField(upload_to="static/img")
	desc = models.TextField()

	def __str__(self):
		return self.title

home/views.py
from django.shortcuts import render, HttpResponse
from django.http import HttpResponseRedirect
from .models import Report

def retrieve(request, id):
	try:
		report = Report.objects.get(id=id)
	except:
		return HttpResponseRedirect("/")
	return render(request, 'report-retrieve.html', {"report" : report})

def index(request):
	reports = Report.objects.all()
	return render(request, 'report-index.html', {"reports" : reports})

home/templates/report-index.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
{% endblock %}
{% block content %}

{% if user.is_authenticated %}
{% else %}
	<a class="lead" href="{% url 'account:login' %}">Log in</a>
{% endif %}

<h1 class="judul my-5"><center>Berita</center></h1>
<div class="container my-5">
	<div class="row">
	{% if reports %}
		{% for report in reports %}
		<div class= "col-sm-12 col-md-6 col-lg-4">
			<center>
				<br>
				<div class="card" style="height: 450px;">
				  <img class="card-img-top" src="/{{ report.image }}">
				  <div class="card-body">
				  	<h5 ><a href="{% url 'report-retrieve' id=report.id %}" style="color:orange;"> <h5 class="card-title"> {{report.title}} </a></h5>
				    <p class="card-text"> {{ report.desc|truncatechars_html:100 }} </p>
				  </div>
				</div>
			</center>
		</div>
		{% endfor %}
		{% else %}
		{% endif %}
	</div>

</div>

{% endblock %}

home/templates/report-retrieve.html
{%extends 'base.html'%}

{% load static %}

{% block style %}

	<link rel="stylesheet" type="text/css" href={% static "news/news.css" %}>

{% endblock %}

{% block content %}

    <div class="container my-5">
    	<div class="row">
    		<div class="col-md-12">
    			{% if report %}
    				<img style="" src="/{{report.image}}" alt="My image">
    				<h1>{{ report.title }}</h1>
    				<p>{{report.desc}}</p>
    			{% endif %}
    		</div>
    	</div>
    </div>

{% endblock %}