account/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "account"

urlpatterns = [
    # path('', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', index, name='home-index'),
    path('<int:id>/', retrieve, name='report-retrieve')
]

tp1ppw/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from home.views import index as home_index
from account.views import *
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#from news.views import news_page
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('account/register/', register, name='register'),
    # path('account/login/', login, name='login_user'),
    # path('account/', include('django.contrib.auth.urls')),
	path('account/', include('account.urls', namespace='account')),
    path('donation/', include('donation.urls'), name='donation'),
    path('home/', include('home.urls'), name='home'),
    path('news/', include('news.urls'), name='news'),
    path('about/', include('about.urls'), name='about'),
	path('auth/', include('social_django.urls', namespace='auth')),
    path('', index, name='index'),
    path('donatur/', include('donatur.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += staticfiles_urlpatterns()

templates/partials/_footer.html
<footer class="page-footer font-small blue pt-4 ftr">
    <div class="container-fluid  text-md-left">
        <div class="row">
            <div class="col-md-8 col-sm-6 justify-content-sm-center">
                <h5 class="text-uppercase YSP">  Yayasan Sinar Perak</h5>
                <p class="alamat"><img src="https://image.flaticon.com/icons/svg/25/25694.svg" style="max-width: 30px;">  Jl. Margonda Raya no. 25</p>
                <p class="tlp"><img src="https://image.flaticon.com/icons/svg/17/17216.svg" style="max-width: 30px;">  (021) 3210654</p>
                <p class="tlp"><img src="https://image.flaticon.com/icons/svg/134/134735.svg" style="max-width: 30px;">  +628-123-456-00</p>
                <p class="email"><img src="https://image.flaticon.com/icons/svg/25/25236.svg" style="max-width: 30px;">  sinarperak@yayasan.com</p>
            </div>

            <div class="col-md-4 col-sm-6 mx-auto">
                <div class="row">
                    <div class="col-xs-3 mx-auto">
                        <img class="responsive" src="https://image.flaticon.com/icons/svg/69/69407.svg">
                    </div>
                    <div class="col-xs-3 mx-auto">
                        <img class="responsive" src="https://image.flaticon.com/icons/svg/69/69406.svg">
                    </div>
                    <div class="col-xs-3 mx-auto">
                        <img class="responsive" src="https://image.flaticon.com/icons/svg/69/69480.svg">
                    </div>
                    <div class="col-xs-3 mx-auto">
                        <img class="responsive" src="https://image.flaticon.com/icons/svg/69/69366.svg">
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
  <img src = "https://image.flaticon.com/icons/svg/179/179251.svg" style="min-width: 40px; margin-right: 7%;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="navbar-nav mr-auto">
        <form class="form-inline" action="{% url 'index' %}" method="GET">
          <div class="form-group">
            <input class="form-control mr-sm-2" id="search" name="search" type="search" placeholder="Cari...." aria-label="Search">
            <button class="form-control btn btn-outline-success my-2 my-sm-0 cari" type="submit">Cari</button>
          </div>
        </form>
      </li>
    </ul>

    <div class="form-inline my-2 my-lg-0">

        <button class="btn btn-default beranda"><a class="nav-link" href="{% url 'home-index' %}">Berita</a></button>
        <button class="btn btn-default beranda"><a class="nav-link" href="{% url 'news-index' %}">Program</a> </button>
        <button class="btn btn-default beranda"><a class="nav-link" href="{% url 'donate-index' %}">Donasi</a> </button>
        <button class="btn btn-default beranda"><a class="nav-link" href="{% url 'testimoni' %}">Tentang Kami</a> </button>
        {% if user.is_authenticated %}
        <button onclick="myDonation()" class="btn btn-default beranda"><a class="nav-link">Profil</a> </button>
          <span class="mr-2">Welcome, {{ user.username }} </span>
          <button class="btn btn-default daftar"><a class="nav-link" href="{% url 'account:logout' %}"> Logout </a> </button>
        {% else %}
          <button class="btn btn-default masuk"><a class="nav-link" href="{% url 'social:begin' 'google-oauth2' %}?next={{request.path}}"> Masuk </a> </button>
        {% endif %}
    </div>
    <script type="text/javascript">
      function myDonation() {
        console.log("hello")
        $.ajax({
          url:"/donatur/",
          method:"GET",
          success: function(data) {
            $("body").html(data);
          }
        })
      }
    </script>
</nav>