donation/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

urlpatterns = [
	path('', index, name = 'donate-index'),
	path('donate/', donate, name = 'donate'),
	path('terimakasih/', terimakasih, name = 'terimakasih'),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', index, name='home-index'),
    path('<int:id>/', retrieve, name='report-retrieve')
]

tp1ppw/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from home.views import index as home_index
from account.views import *
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#from news.views import news_page
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('account/register/', register, name='register'),
    # path('account/login/', login, name='login_user'),
    # path('account/', include('django.contrib.auth.urls')),
	path('account/', include('account.urls', namespace='account')),
    path('donation/', include('donation.urls'), name='donation'),
    path('home/', include('home.urls'), name='home'),
    path('news/', include('news.urls'), name='news'),
    path('about/', include('about.urls'), name='about'),
	path('auth/', include('social_django.urls', namespace='auth')),
    path('', index, name='index'),
    path('donatur/', include('donatur.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += staticfiles_urlpatterns()

donation/models.py
from django.db import models

class Donation(models.Model):
    program = models.ForeignKey("news.News", on_delete=models.CASCADE)
    donatur_fullname = models.CharField(max_length=100)
    donatur_email = models.CharField(max_length=100)
    total_donation = models.FloatField()
    is_anon = models.BooleanField()

donation/forms.py
from django import forms
from news.models import News
from .models import Donation

class DonationForm(forms.ModelForm):
    program = forms.ModelChoiceField(queryset=News.objects.all())
    is_anon = forms.BooleanField(initial=False, required=False)

    class Meta:
        model = Donation
        fields = ('program', 'donatur_fullname', 'donatur_email', 'total_donation', 'is_anon')
        labels = {
            "is_anon": "Ingin berdonasi secara Anonymous?",
        }

    def __init__(self, *args, **kwargs):
        super(DonationForm, self).__init__(*args, **kwargs)
        self.fields['total_donation'].widget.attrs['min'] = 1000
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        self.fields['is_anon'].widget.attrs['class'] = ""

donation/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.http import JsonResponse
from django.urls import reverse
from .forms import DonationForm
from account.forms import ProfileForm
from .models import Donation
from news.models import News
from account.views import *
from account.models import Profile

# Create your views here.
def index(request):
	response = {}
	try:
		form = DonationForm(request.POST or None,  initial=
						{"donatur_email" : request.user.email,
						"donatur_fullname" : request.user.first_name + request.user.last_name})
	except:
		form = DonationForm(request.POST or None)
	return render(request, 'donation.html', {'form': form})

def donate(request):
	form = DonationForm(request.POST or None)
	if(request.method == "POST"):
		if(not request.user.is_authenticated):
			return JsonResponse({"message" : "You haven't logged in, please login", "status_code": 403})
		if(form.is_valid):
			print(request.POST)
			program_id = request.POST['program']
			program = News.objects.get(pk=program_id)
			total_donation = request.POST['total_donation']
			is_anon = True if str(request.POST['is_anon']) == "true" else False
			Donation.objects.create(program=program,
								donatur_fullname=request.user.first_name + request.user.last_name,
								total_donation=total_donation,
								donatur_email=request.user.email,
								is_anon=is_anon)
			return JsonResponse({"message" : "Success", "status_code": 200})
		return JsonResponse({"message" : "Data is not valid", "status_code":403})
	else:
		return JsonResponse({"message" : "/GET method is not allowed"})


def terimakasih(request):
	return render(request,'terimakasih.html')

donation/templates/donation.html
{% extends 'base.html' %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Error</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
				Silahkan untuk login dulu sebelum berdonasi
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary"><a href="{% url 'social:begin' 'google-oauth2' %}?next={{request.path}}">Login</a></button>
      </div>
    </div>
  </div>
</div>

<div class="container my-5">
	<div class="col">
		<div class="row">
			<div class="col-md-12">
				<div class="row justify-content-md-center">
					<div class="col-md-8 justify-content-md-center">
						<center>
							<div class="border border-secondary " aria-label="breadcrumb" style="width:104%">
								<div class="border border-secondary" style="background-color: #2DB49F">
									<br>
									<p style="font-size: 30px"><strong>Form Donasi</strong></p>
											{% if message %}
												<small style="color:red" class="my-5">Email belum terdaftar, silahkan mendaftar</small>
											{% endif %}
								</div>
								<div id="donation-page" class="bg-grey" style="height:100%;">
									<div style="width: 60%">
										<br>
											{% csrf_token %}
											{% for field in form %}
												<div class="form-group">
													{{ field.label }}
													{{ field }}
												</div>
											{% endfor %}
											<button onclick="donateSubmit()" id="donate-btn" class="btn btn-success">Donasikan</button>
											<br>
											<small class="my-5">Anda belum bisa berdonasi jika email anda belum teregistrasi</small>
									</div>
								</div>
								{% if form.errors %}
									{% for field in form %}
										{% for error in field.errors %}
											<div class="alert alert-danger">
												<strong>{{ error|escape }}</strong>
											</div>
										{% endfor %}
									{% endfor %}
									{% for error in form.non_field_errors %}
										<div class="alert alert-danger">
											<strong>{{ error|escape }}</strong>
										</div>
									{% endfor %}
								{% endif %}
							</div>
						</center>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block extrajs %}
	<script>
    console.log($("#id_is_anon"))

		function donateSubmit() {
			data = {
				total_donation: $("#id_total_donation").val(),
				program: $("#id_program").val(),
				is_anon: $("#id_is_anon")[0].checked,
				donatur_fullname: $("#id_donatur_fullname").val(),
				donatur_name: $("#id_donatur_name").val(),
    		csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value,
			}
			submitDonation(data);
		}

		function submitDonation(data) {
			$.ajax({
				url: "donate/",
				type: "POST",
				data: data
			})
			.done((response) => {
				if(response['status_code'] == 403) {
					$('#exampleModalCenter').modal('show');
				} else if (response['status_code'] == 200) {
					alert("Berhasill")
					window.location.replace("terimakasih/");
				} else {
					alert("error occured")
				}
			})
			.fail()
		}

	</script>
{% endblock %}

donation/templates/terimakasih.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="col">
    	<div class="row">
    		<div class="col-12">
    			<br><br><br><br>
      		</div>
      	</div>
      	<div class="row">
    		<div class="col-12">
    				<div class="row justify-content-md-center">
    					<div class="col-md-8 " style="width: 70%">
              <div class="terimakasih">	
    						<div class= "border border-secondary" style="background-color: #2DB49F">
								<br><br><br><br><br><br>
								<div style="margin: 5% 5%">
								  <h1 class="display-4">Terima Kasih Sudah Melakukan Donasi</h1>
								<p class="lead">Konfirmasi donasi akan dikirimkan ke email anda</p>
                <a href="/" class="btn btn-light btn-lg active" role="button" aria-pressed="true">Kembali ke Beranda</a>
							</div>
							</div>
            </div>
								<br><br><br>
						</div>
					</div>
      		</div>
      	</div>
      	<div class="row">
    		<div class="col-12">
    			<br><br><br><br>
      		</div>
      	</div>
    </div>
</div>

  
{% endblock %}